name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: aandrade007  # Substitua pelo seu usuário GitHub
          outputs: dist/snake.svg
          
      - name: Upload the generated snake.svg
        uses: actions/upload-artifact@v4
        with:
          name: snake-graph
          path: dist/snake.svg

      - name: Push generated snake image to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
