name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: aandrade007  # Seu usuário GitHub
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist/snake.svg
      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
