name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualizar todos os dias
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: aandrade007
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
